name: "unit-test-cronjob"

on:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  # test action works running from the schedule
  cronjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        milliseconds: 1000
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALGOLIA_APPID: ${{ secrets.ALGOLIA_APPID }}
        ALGOLIA_APP_KEY: ${{ secrets.ALGOLIA_APP_KEY }}